#!/usr/bin/env bash

echo "Resetting SMNRP..."
rm -rf /etc/letsencrypt/accounts
rm -rf /etc/letsencrypt/archive
rm -rf /etc/letsencrypt/csr
rm -rf /etc/letsencrypt/keys
rm -rf /etc/letsencrypt/live/*
rm -rf /etc/letsencrypt/renewal
rm -rf /etc/letsencrypt/last_renew.ts
echo "DONE, you can now relaunch the container..."