name: ci
on: 
  push:
    branches:
      - 'main'
    tags:
      - "v*"

jobs:
  docker:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          # list of Docker images to use as base name for tags
          images: |
            ethnexus/smnrp            
          # generate Docker tags based on the following events/attributes
          tags: |
            # type=schedule
            type=ref,event=branch
            type=ref,event=pr
            # type=sha
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - 
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ethnexus
          password: ${{ secrets.DOCKER_PASS }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          # tags: ethnexus/smnrp:latest,ethnexus/smnrp:1.0.0
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  PushContainerReadme:
    runs-on: ubuntu-latest
    name: Push README to Docker Hub
    steps:
      - 
        name: git checkout
        uses: actions/checkout@v3
      - 
        name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: ethnexus
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        with:
          destination_container_repo: ethnexus/smnrp
          provider: dockerhub
          short_description: 'Secure Multifunctional Nginx Reverse Proxy'
          readme_file: 'README.md'